name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: windows-11-arm

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup lde
        uses: lde-org/setup-lde@master
        with:
          version: nightly

      - name: Run tests
        run: lde test
